import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import random
from typing import Dict, Any
import pytorch_lightning as pl
import torch.optim as optim

class ControllerLightning(pl.LightningModule):
    def __init__(self, settings: Dict[str, Any], model_pretrained: nn.Module=None):
        super().__init__()
        self.save_hyperparameters(settings)
        self.name_model = "writing_controller"

        # Parameters
        self.dim_embedding_key = self.hparams["dim_embedding_key"]
        self.num_prediction = self.hparams["num_prediction"]
        self.past_len = self.hparams["past_len"]
        self.future_len = self.hparams["future_len"]

        # Memory Bank Buffers
        self.register_buffer("memory_past", torch.empty(0, self.dim_embedding_key))
        self.register_buffer("memory_fut", torch.empty(0, self.dim_embedding_key))

        if model_pretrained is not None:
            self.conv_past = model_pretrained.conv_past
            self.conv_fut = model_pretrained.conv_fut
            self.encoder_past = model_pretrained.encoder_past
            self.encoder_fut = model_pretrained.encoder_fut
            self.decoder = model_pretrained.decoder
            self.FC_output = model_pretrained.FC_output
        else:
            # Architecture Skeleton (Must match ModelEncoderLightning exactly)
            channel_in, channel_out, dim_key = 3, 16, self.dim_embedding_key
            self.conv_past = nn.Conv1d(channel_in, channel_out, 3, padding=1)
            self.conv_fut = nn.Conv1d(channel_in, channel_out, 3, padding=1)
            self.encoder_past = nn.GRU(channel_out, dim_key, 1, batch_first=True)
            self.encoder_fut = nn.GRU(channel_out, dim_key, 1, batch_first=True)
            self.decoder = nn.GRU(dim_key * 2, dim_key * 2, 1, batch_first=False)
            self.FC_output = nn.Linear(dim_key * 2, 3)

        # Layers (re-use pretrained components)
        # self.conv_past = model_pretrained.conv_past
        # self.conv_fut = model_pretrained.conv_fut
        # self.encoder_past = model_pretrained.encoder_past
        # self.encoder_fut = model_pretrained.encoder_fut
        # self.decoder = model_pretrained.decoder
        # self.FC_output = model_pretrained.FC_output

        # Freeze AE layers
        for part in [self.conv_past, self.conv_fut, 
                     self.encoder_past, self.encoder_fut, 
                     self.decoder, self.FC_output]:
            for param in part.parameters():
                param.requires_grad = False

        self.relu = nn.ReLU()
        self.linear_controller = nn.Linear(1, 1)

    def on_load_checkpoint(self, checkpoint: Dict[str, Any]) -> None:
        """
        Lightning Hook: This runs BEFORE load_state_dict.
        We resize our buffers to match the checkpoint size so the loading doesn't crash.
        """
        if "state_dict" in checkpoint:
            # Extract the shape from the saved checkpoint
            past_shape = checkpoint["state_dict"]["memory_past"].shape
            fut_shape = checkpoint["state_dict"]["memory_fut"].shape
            
            # Re-initialize the buffers to the correct size
            self.memory_past = torch.empty(past_shape, device=self.device)
            self.memory_fut = torch.empty(fut_shape, device=self.device)

    def ControllerLoss(self, prob, sim):
        """
        Loss to train writing controller:
        :param prob: writing probability generated by controller
        :param sim: similarity (between 0 and 1) between better prediction and ground-truth.
        :return: loss
        """
        loss = prob * sim + (1 - prob) * (1 - sim)
        return torch.sum(loss)


    def init_memory(self, data_train):
        self.memory_past = torch.empty(0, self.dim_embedding_key, device=self.device)
        self.memory_fut = torch.empty(0, self.dim_embedding_key, device=self.device)
        self.eval() 
        with torch.no_grad():
            for _ in range(self.num_prediction + 1):
                j = random.randint(0, len(data_train) - 1)
                sample = data_train[j]
                past = sample["past"].unsqueeze(0).to(self.device)
                future = sample["future"].unsqueeze(0).to(self.device)

                past_t = past.transpose(1, 2)
                story_embed = self.relu(self.conv_past(past_t)).transpose(1, 2)
                _, state_past = self.encoder_past(story_embed)

                fut_t = future.transpose(1, 2)
                future_embed = self.relu(self.conv_fut(fut_t)).transpose(1, 2)
                _, state_fut = self.encoder_fut(future_embed)

                self.memory_past = torch.cat((self.memory_past, state_past.squeeze(0)), 0)
                self.memory_fut = torch.cat((self.memory_fut, state_fut.squeeze(0)), 0)
        self.train()

    def _memory_writing(self):
        """
        Writing in the memory with controller (loop over all train dataset).
        In Lightning, we call this at the start of the epoch.
        """
        train_loader = self.trainer.train_dataloader
        self.init_memory(self.trainer.train_data)
        
        self.eval()
        with torch.no_grad():
            for batch in train_loader:
                past, future = batch["past"].to(self.device), batch["future"].to(self.device)
                # Calling forward in training mode (with future) triggers memory writing
                _, _ = self.forward(past, future)
        self.train()

    def on_train_epoch_start(self):
        """
        Lightning Hook: Triggered at the start of every epoch to reset and refill memory.
        """
        print(f"\nEpoch {self.current_epoch}: Initializing and writing memory...")
        self._memory_writing()

    def forward(self, past, future=None):
        dim_batch = past.size(0)
        zero_padding = torch.zeros(1, dim_batch, self.dim_embedding_key * 2, device=self.device)
        prediction = torch.empty(0, device=self.device) 
        present_temp = past[:, -1].unsqueeze(1) 

        # past temporal encoding
        past_t = past.transpose(1, 2)
        story_embed = self.relu(self.conv_past(past_t)).transpose(1, 2)
        _, state_past = self.encoder_past(story_embed) 

        # Memory Read Logic
        past_norm = F.normalize(self.memory_past, p=2, dim=1)
        state_norm = F.normalize(state_past.squeeze(0), p=2, dim=1)
        weight_read = torch.matmul(state_norm, past_norm.t())
        index_max = torch.sort(weight_read, descending=True, dim=1)[1]

        for i_track in range(self.num_prediction):
            present = present_temp
            prediction_single = torch.empty(0, device=self.device)
            ind = index_max[:, i_track] 
            info_future = self.memory_fut[ind] 
            info_total = torch.cat((state_past, info_future.unsqueeze(0)), 2) 
            
            input_dec = info_total
            state_dec = zero_padding
            for _ in range(self.future_len):
                output_decoder, state_dec = self.decoder(input_dec, state_dec)
                disp = self.FC_output(output_decoder) 
                coords_next = present + disp.squeeze(0).unsqueeze(1) 
                prediction_single = torch.cat((prediction_single, coords_next), 1) 
                present = coords_next
                input_dec = zero_padding
            prediction = torch.cat((prediction, prediction_single.unsqueeze(1)), 1) 

        # Writing Logic (Used during _memory_writing or training_step)
        if future is not None:
            future_rep = future.unsqueeze(1).repeat(1, self.num_prediction, 1, 1)
            distances = torch.norm(prediction - future_rep, dim=3) 

            t1 = torch.sum(distances[:, :, :10] < 0.5, dim=2)
            t2 = torch.sum(distances[:, :, 10:20] < 1.0, dim=2)
            t3 = torch.sum(distances[:, :, 20:30] < 1.5, dim=2)
            t4 = torch.sum(distances[:, :, 30:40] < 2.0, dim=2)
            
            tolerance_rate = torch.max(t1+t2+t3+t4, dim=1)[0].float() / 40.0
            tolerance_rate = tolerance_rate.unsqueeze(1) 

            writing_logits = self.linear_controller(tolerance_rate)
            writing_prob = torch.sigmoid(writing_logits)

            # Check if we should write this batch to memory
            if not self.training: # Usually we write to memory during the _memory_writing phase
                index_writing = (writing_prob > 0.5).squeeze()
                if index_writing.any():
                    fut_t = future.transpose(1, 2)
                    fut_embed = self.relu(self.conv_fut(fut_t)).transpose(1, 2)
                    _, state_fut = self.encoder_fut(fut_embed)
                    self.memory_past = torch.cat((self.memory_past, state_past.squeeze(0)[index_writing]), 0)
                    self.memory_fut = torch.cat((self.memory_fut, state_fut.squeeze(0)[index_writing]), 0)

            return writing_prob, tolerance_rate

        return prediction

    def training_step(self, batch, batch_idx):
        past, future = batch["past"], batch["future"]
        
        # 1. Forward pass returns (prob, sim)
        prob, sim = self(past, future)
        
        # 2. Call original ControllerLoss
        loss = self.ControllerLoss(prob, sim)
        
        self.log("val_loss", loss, prog_bar=True, on_epoch=True)
        self.log("mem/size", float(self.memory_past.shape[0]), on_epoch=True)
        return loss

    def configure_optimizers(self):
        return optim.Adam(filter(lambda p: p.requires_grad, self.parameters()), lr=self.hparams["learning_rate"])

class model_controllerMem(nn.Module):
    """
    Writing Controller (MANTRA) — trajectory-only

    Same structure as original:
      - conv_past/conv_fut
      - encoder_past/encoder_fut
      - cosine similarity memory read
      - decoder autoregressive rollout
      - FC_output predicts displacement
      - coords_next = present + displacement

    Updated for 3D trajectories (x,y,z).
    Expects:
      past:   (B, Tp, 3)
      future: (B, Tf, 3) (optional)
    Produces:
      prediction: (B, num_prediction, Tf, 3) when future is None
      or (writing_prob, tolerance_rate) when future is provided (training)
    """

    def __init__(self, settings, model_pretrained):
        super(model_controllerMem, self).__init__()
        self.name_model = "writing_controller"

        # parameters
        self.use_cuda = settings["use_cuda"]
        self.dim_embedding_key = settings["dim_embedding_key"]
        self.num_prediction = settings["num_prediction"]
        self.past_len = settings["past_len"]
        self.future_len = settings["future_len"]

        # coordinate dimension (3D)
        self.coord_dim = 3

        # similarity criterion
        self.weight_read = []
        self.index_max = []
        self.similarity = nn.CosineSimilarity(dim=1)

        # Memory
        self.memory_past = torch.empty(0)
        self.memory_fut = torch.empty(0)
        self.memory_count = []

        # layers (re-use pretrained components)
        self.conv_past = model_pretrained.conv_past
        self.conv_fut = model_pretrained.conv_fut

        self.encoder_past = model_pretrained.encoder_past
        self.encoder_fut = model_pretrained.encoder_fut
        self.decoder = model_pretrained.decoder
        self.FC_output = model_pretrained.FC_output

        # activation functions
        self.relu = nn.ReLU()
        self.softmax = nn.Softmax(dim=1)

        self.linear_controller = torch.nn.Linear(1, 1)

        if self.use_cuda:
            self.cuda()

    def _device(self):
        return next(self.parameters()).device

    def init_memory(self, data_train):
        """
        Initialization: write random samples in memory.
        Expects dataset __getitem__ to return:
          [.., past, future, ..]
        consistent with original MANTRA dataset indexing.
        """

        device = self._device()
        self.memory_past = torch.empty(0, self.dim_embedding_key, device=device)
        self.memory_fut = torch.empty(0, self.dim_embedding_key, device=device)

        for _ in range(self.num_prediction + 1):
            j = random.randint(0, len(data_train) - 1)
            past = data_train[j][1].unsqueeze(0).to(device)    # (1,Tp,3)
            future = data_train[j][2].unsqueeze(0).to(device)  # (1,Tf,3)

            # past encoding
            past_t = torch.transpose(past, 1, 2)                 # (1,3,Tp)
            story_embed = self.relu(self.conv_past(past_t))      # (1,C',Tp) depends on conv
            story_embed = torch.transpose(story_embed, 1, 2)     # (1,Tp,C')
            _, state_past = self.encoder_past(story_embed)       # state_past: (1,1,K) or (L,1,K)

            # future encoding
            fut_t = torch.transpose(future, 1, 2)
            future_embed = self.relu(self.conv_fut(fut_t))
            future_embed = torch.transpose(future_embed, 1, 2)
            _, state_fut = self.encoder_fut(future_embed)

            # insert in memory
            # state_* expected shape (1,1,K) in original code after squeeze(0) -> (1,K)
            self.memory_past = torch.cat((self.memory_past, state_past.squeeze(0)), 0)
            self.memory_fut = torch.cat((self.memory_fut, state_fut.squeeze(0)), 0)

    def check_memory(self, index):
        """
        Generate a future track from a stored memory index.
        """
        device = self._device()

        mem_past_i = self.memory_past[index]  # (K,)
        mem_fut_i = self.memory_fut[index]    # (K,)

        zero_padding = torch.zeros(1, 1, self.dim_embedding_key * 2, device=device)
        present = torch.zeros(1, self.coord_dim, device=device)  # (1,3)
        prediction_single = torch.empty(0, device=device)

        info_total = torch.cat((mem_past_i, mem_fut_i), 0)       # (2K,)
        input_dec = info_total.unsqueeze(0).unsqueeze(0)         # (1,1,2K)
        state_dec = zero_padding                                 # (1,1,2K) for their decoder

        for _ in range(self.future_len):
            output_decoder, state_dec = self.decoder(input_dec, state_dec)
            displacement_next = self.FC_output(output_decoder)   # should be (1,1,3)
            coords_next = present + displacement_next.squeeze(0).unsqueeze(1)  # (1,1,3)
            prediction_single = torch.cat((prediction_single, coords_next), 1) # (1,t,3)
            present = coords_next
            input_dec = zero_padding

        return prediction_single

    def forward(self, past, future=None):
        """
        Test phase (future=None):
          returns prediction: (B, num_prediction, Tf, 3)

        Train phase (future provided):
          returns (writing_prob, tolerance_rate) and writes to memory for items passing controller
        """
        device = self._device()

        dim_batch = past.size(0)
        zero_padding = torch.zeros(1, dim_batch, self.dim_embedding_key * 2, device=device)
        prediction = torch.empty(0, device=device)  # will cat along pred dimension
        present_temp = past[:, -1].unsqueeze(1)     # (B,1,3)

        # past temporal encoding
        past_t = torch.transpose(past, 1, 2)             # (B,3,Tp)
        story_embed = self.relu(self.conv_past(past_t))
        story_embed = torch.transpose(story_embed, 1, 2)
        _, state_past = self.encoder_past(story_embed)   # (1,B,K) or (L,B,K)

        # Cosine similarity and memory read (exact original logic)
        past_normalized = F.normalize(self.memory_past, p=2, dim=1)                 # (M,K)
        state_normalized = F.normalize(state_past.squeeze(), p=2, dim=1)           # (B,K)
        self.weight_read = torch.matmul(
            past_normalized, state_normalized.transpose(0, 1)
        ).transpose(0, 1)                                                          # (B,M)
        self.index_max = torch.sort(self.weight_read, descending=True)[1].cpu()    # (B,M)

        # Decode for top-k retrieved futures
        for i_track in range(self.num_prediction):
            present = present_temp
            prediction_single = torch.empty(0, device=device)
            ind = self.index_max[:, i_track]              # (B,)
            info_future = self.memory_fut[ind.to(device)] # (B,K)

            # concatenate current state_past with retrieved future embedding
            # state_past expected (1,B,K) ; info_future.unsqueeze(0) -> (1,B,K)
            info_total = torch.cat((state_past, info_future.unsqueeze(0)), 2)  # (1,B,2K)
            input_dec = info_total
            state_dec = zero_padding

            for _ in range(self.future_len):
                output_decoder, state_dec = self.decoder(input_dec, state_dec)
                displacement_next = self.FC_output(output_decoder)  # (1,B,3)
                coords_next = present + displacement_next.squeeze(0).unsqueeze(1)  # (B,1,3)
                prediction_single = torch.cat((prediction_single, coords_next), 1) # (B,t,3)
                present = coords_next
                input_dec = zero_padding

            prediction = torch.cat((prediction, prediction_single.unsqueeze(1)), 1) # (B,i_track,t,3)

        # === Training phase (writing controller) ===
        if future is not None:
            # future: (B,Tf,3)
            future_rep = future.unsqueeze(1).repeat(1, self.num_prediction, 1, 1)   # (B,K,Tf,3)
            distances = torch.norm(prediction - future_rep, dim=3)                  # (B,K,Tf)

            # NOTE: thresholds are in *meters* if xyz is meters.
            # Your z is altitude (negative down in NED) - still meters, so OK.
            tolerance_1s = torch.sum(distances[:, :, :10] < 0.5, dim=2)
            tolerance_2s = torch.sum(distances[:, :, 10:20] < 1.0, dim=2)
            tolerance_3s = torch.sum(distances[:, :, 20:30] < 1.5, dim=2)
            tolerance_4s = torch.sum(distances[:, :, 30:40] < 2.0, dim=2)
            tolerance = tolerance_1s + tolerance_2s + tolerance_3s + tolerance_4s

            tolerance_rate = torch.max(tolerance, dim=1)[0].float() / 40.0          # (B,)
            tolerance_rate = tolerance_rate.unsqueeze(1).to(device)                 # (B,1)

            writing_prob = torch.sigmoid(self.linear_controller(tolerance_rate))    # (B,1)

            # future encoding (for candidates to write)
            fut_t = torch.transpose(future, 1, 2)             # (B,3,Tf)
            future_embed = self.relu(self.conv_fut(fut_t))
            future_embed = torch.transpose(future_embed, 1, 2)
            _, state_fut = self.encoder_fut(future_embed)     # (1,B,K)

            index_writing = np.where(writing_prob.detach().cpu().numpy() > 0.5)[0]
            if len(index_writing) > 0:
                past_to_write = state_past.squeeze()[index_writing]   # (n,K)
                future_to_write = state_fut.squeeze()[index_writing]  # (n,K)

                self.memory_past = torch.cat((self.memory_past, past_to_write), 0)
                self.memory_fut = torch.cat((self.memory_fut, future_to_write), 0)

            return writing_prob, tolerance_rate

        # === Test phase ===
        return prediction

    def write_in_memory(self, past, future):
        """
        Same as original: decides if past-future will be inserted in memory.
        Uses tolerance-based writing controller.
        """
        device = self._device()

        if self.memory_past.shape[0] < self.num_prediction:
            num_prediction = int(self.memory_past.shape[0])
        else:
            num_prediction = self.num_prediction

        dim_batch = past.size(0)
        zero_padding = torch.zeros(1, dim_batch, self.dim_embedding_key * 2, device=device)
        prediction = torch.empty(0, device=device)
        present_temp = past[:, -1].unsqueeze(1)

        # past temporal encoding
        past_t = torch.transpose(past, 1, 2)
        story_embed = self.relu(self.conv_past(past_t))
        story_embed = torch.transpose(story_embed, 1, 2)
        _, state_past = self.encoder_past(story_embed)

        # Cosine similarity and memory read
        past_normalized = F.normalize(self.memory_past, p=2, dim=1)
        state_normalized = F.normalize(state_past.squeeze(), p=2, dim=1)
        weight_read = torch.matmul(past_normalized, state_normalized.transpose(0, 1)).transpose(0, 1)
        index_max = torch.sort(weight_read, descending=True)[1].cpu()[:, :num_prediction]

        for i_track in range(num_prediction):
            present = present_temp
            prediction_single = torch.empty(0, device=device)
            ind = index_max[:, i_track]
            info_future = self.memory_fut[ind.to(device)]
            info_total = torch.cat((state_past, info_future.unsqueeze(0)), 2)
            input_dec = info_total
            state_dec = zero_padding

            for _ in range(self.future_len):
                output_decoder, state_dec = self.decoder(input_dec, state_dec)
                displacement_next = self.FC_output(output_decoder)  # (1,B,3)
                coords_next = present + displacement_next.squeeze(0).unsqueeze(1)
                prediction_single = torch.cat((prediction_single, coords_next), 1)
                present = coords_next
                input_dec = zero_padding

            prediction = torch.cat((prediction, prediction_single.unsqueeze(1)), 1)

        future_rep = future.unsqueeze(1).repeat(1, num_prediction, 1, 1)
        distances = torch.norm(prediction - future_rep, dim=3)

        tolerance_1s = torch.sum(distances[:, :, :10] < 0.5, dim=2)
        tolerance_2s = torch.sum(distances[:, :, 10:20] < 1.0, dim=2)
        tolerance_3s = torch.sum(distances[:, :, 20:30] < 1.5, dim=2)
        tolerance_4s = torch.sum(distances[:, :, 30:40] < 2.0, dim=2)
        tolerance = tolerance_1s + tolerance_2s + tolerance_3s + tolerance_4s

        tolerance_rate = torch.max(tolerance, dim=1)[0].float() / 40.0
        tolerance_rate = tolerance_rate.unsqueeze(1).to(device)

        writing_prob = torch.sigmoid(self.linear_controller(tolerance_rate))

        # future encoding
        fut_t = torch.transpose(future, 1, 2)
        future_embed = self.relu(self.conv_fut(fut_t))
        future_embed = torch.transpose(future_embed, 1, 2)
        _, state_fut = self.encoder_fut(future_embed)

        index_writing = np.where(writing_prob.detach().cpu().numpy() > 0.5)[0]
        if len(index_writing) > 0:
            past_to_write = state_past.squeeze()[index_writing]
            future_to_write = state_fut.squeeze()[index_writing]
            self.memory_past = torch.cat((self.memory_past, past_to_write), 0)
            self.memory_fut = torch.cat((self.memory_fut, future_to_write), 0)

        return writing_prob, tolerance_rate
